### ISSUE TITLE
Backend task list :

### ISSUE THREAD

**Issue by firdausbaihaqi** [firdausbaihaqi/it-clinic#2]
- [x] nge link antar halaman
- [x] list request customer
- [x] list request technician
- [x] Add upload picture
