### ISSUE TITLE
Frontend task list :

### ISSUE THREAD

**Issue by firdausbaihaqi** [firdausbaihaqi/it-clinic#3]
make progress on : 

  - [x]  dashboard admin
  - [x]  tambah halaman baru untuk edit oleh admin
  - [x]  customer page (rework)
  - [x]  technician page (rework)
  - [x] tambah icon notif dll
  - [x]  tambahkan modal detail di dashboard cust dan teknisi
  - [x]  tambahkan button detail di dashboard cust dan teknisi
  - [x]  tambah button siap antar pada dashboard customer
  - [x]  tambahkan foto di verify admin detail
 -  [x] confirmation -user.php revisi
