### ISSUE TITLE
Reviewer task list :

### ISSUE THREAD

**Issue by firdausbaihaqi** [firdausbaihaqi/it-clinic#5]
- [ ] tinjau ulang fitur2 it-clinic
- [ ] tambahkan ide tentang fitur it clinic (opsional, centang kalau tidak ada)
- [ ] ingatkan team jika ada list fitur yang dirasa bermasalah atau tidak penting
